build: disable `win_arm64` for now
build fails with:

> error: linking with `link.exe` failed: exit code: 1120

because of 54 unresolved external symbols (`error LNK2019`).

plus `libopenssl_sys` warns:

> warning LNK4272: library machine type 'ARM64' conflicts with target machine type 'x64'